//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMultitierLong
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int HouseId { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public int Price { get; set; }
        public int NumberOfRoom { get; set; }
        public int NumberOfBathroom { get; set; }
        public string Garage { get; set; }
        public string Pool { get; set; }
        public string Fireplace { get; set; }
    }
}
