//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMultitierLong
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MidtermDatabaseEntities2 : DbContext
    {
        public MidtermDatabaseEntities2()
            : base("name=MidtermDatabaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<NovaScotia> NovaScotias { get; set; }
        public virtual DbSet<NumberOfBathroom> NumberOfBathrooms { get; set; }
        public virtual DbSet<NumberOfRoom> NumberOfRooms { get; set; }
        public virtual DbSet<Ontario> Ontarios { get; set; }
        public virtual DbSet<Quebec> Quebecs { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
